project:
  type: default
  output-dir: _output

format:
  pdf:
    pdf-engine: xelatex
    number-sections: true
    toc: true
    fontsize: 11pt
    geometry:
      - margin=1in
    linestretch: 1.5
