name: fe530-hw1
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - yfinance
  - pip
  - pip:
      - quarto-cli==1.6.39 ; python_version >= '3.10'  # optional if you prefer local Quarto
